name: fixpaynfc
description: Demonstrates how to use the nfc_manager plugin.
publish_to: 'none'

environment:
  sdk: "<4.0.0"

dependencies:
  flutter:
    sdk: flutter
  nfc_manager:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
